### ISSUE TITLE
безопасное удаление ресурса

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#10]
Если создать ресурс, попользоваться им, а потом удалить, пароль от ресурса останется жить на диске, потому что far2l при удалении файлов-ключей реестра вряд ли делает им wipe.

Поэтому разумнее хранить пароли от ресурсов не в реестре, а в обычных файлах где-нибудь в ~/.config/far2l, и делать им wipe (far же это умеет по alt+del; проверял; в linux версии тоже работает) при удалении ресурса.

**Comment by unxed** [comment]
В принципе, можно хранить в отдельны файлах только пароли, а всё остальное оставить как есть.

**Comment by unxed** [comment]
Искомая функция far - WipeFile в delete.cpp

Можно, конечно, попробовать заменить на неё remove(file.c_str()) в APIRegistry.cpp, но не хотелось бы трогать оригинальный far2l для нужд дополнения.

Впрочем,
https://github.com/elfmz/far2l/issues/275

**Comment by unxed** [comment]
А что используется в качестве ключа шифрования? Положим, злоумышленник получил доступ к моей домашней папке, и, соответственно, реестру far2l. Он при этом не сможет стащить и ключ шифрования заодно?

Было бы здорово написать об этом в readme, а также о том, что там AES-256. Для паранойиков вроде меня :)

**Comment by cycleg** [comment]
Безопасное удаление ключей из реестра реализовано в far2l, elfmz/far2l#275.
