### ISSUE TITLE
подсказки по клавишам в нижней панели

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#11]
например, с зажатым шифтом по F8 подсказывает "delete", а логичнее было бы "umount" (по буквам влазит). аналогично F4 "edit.." -> "new...".

**Comment by unxed** [comment]
Остались "лишние" подсказки.
F3, F5, F6, Shift+F1..F3, Shift+F5..F6, Alt+F3..F8, Ctrl+F3..F12 (?)

Ctrl+F4 и Ctrl+F7..F11 переворачивают порядок сортировки ресурсов, не знаю, баг это или фича :)

**Comment by cycleg** [comment]
Стоит вообще закрыть Shift-F5, Shift-F6 и Alt с F3 по F6, включая обработку. Ctrl -- всякие сортировки, повторное нажатие меняет направление. Это еще с Norton Commander так, трогать не стоит. F3, F5, F6 уже блокированы, осталось подсказки убрать.

**Comment by cycleg** [comment]
Стоит вообще закрыть Shift-F5, Shift-F6 и Alt с F3 по F6, включая обработку. Ctrl -- всякие сортировки, повторное нажатие меняет направление. Это еще с Norton Commander так, трогать не стоит. F3, F5, F6 уже блокированы, осталось подсказки убрать.

**Comment by cycleg** [comment]
Стоит вообще закрыть Shift-F5, Shift-F6 и Alt с F3 по F6, включая обработку. Ctrl -- всякие сортировки, повторное нажатие меняет направление. Это еще с Norton Commander так, трогать не стоит. F3, F5, F6 уже блокированы, осталось подсказки убрать.

**Comment by unxed** [comment]
Лишние подсказки исчезли, подтверждаю.
