### ISSUE TITLE
не работает указание начальной папки при соединении по sftp

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#12]
sftp://HOSTNAME/var/www
при соединении всё равно кидает в домашнюю папку пользователя

если нельзя это сделать через URL, можно добавить ещё одно поле, home folder, который бы указывался относительно точки монтирования.

**Comment by cycleg** [comment]
Я не смог подмонтировать конкретную директорию и "руками", через gvfs-mount. Такое впечатление, что адаптер GVFS для SFTP кладет на путь с прибором. Если смонтировать, а потом смотреть в `"/run/user/<uid>/gvfs"`, то там появляется директория, которая смотрит в корень удаленного хоста. А если открыть ссылку на десктопе -- будет корневая директория пользователя. Плагин же в качестве точки монтирования получает такой путь: `"/run/user/<uid>/gvfs/sftp:host=<name or address>/<user home directory>"` и начальной директорией показывает ее же. Если в URL добавить пользователя, то в точку монтирования добавляется после хоста `",user=<user name>"`, больше разницы никакой. Но разные URL -- это таки разные ресурсы, пусть даже "смотрят" на одну и ту же удаленную директорию! Их, похоже, сравнивают просто как строки. В общем, чудеса на виражах.

**Comment by unxed** [comment]
По идее, можно обойти эту "особенность" gvfs, если сделать обработку пути, который идёт в URL после имени хоста, на стороне far-gvfs. Но тогда придётся добавлять как минимум парсинг URL, чего, как я понимаю, делать не хочется из соображений следования принципу KISS.

Тикет в GNOME? ;-)

**Comment by cycleg** [comment]
В документации на класс Gio::Mount или Gio::File есть упоминание, что mount после создания смотрит либо в удаленную домашнюю директорию пользователя, либо в корень удаленной файловой системы. Других вариантов вообще нет, т.е. навигацию надо делать "руками" после монтирования.

**Comment by unxed** [comment]
Напрашивающееся решение: задавать в свойствах ресурса путь относительно точки монтирования по умолчанию, куда плагин бы перекидывал после монтирования. Мне бы этого хватило с лихвой. Если соединение не слишком быстрое, чтение "ненужных" папок "по дороге" до нужной отнимает кучу времени, было бы здорово иметь возможность этого избегать.

**Comment by cycleg** [comment]
А вот тут другой вопрос возник: если приделать мониторинг монтирования (оказалось, это не так страшно, все-таки GIO действительно высокоуровневая штука), то как искать ресурс в списке far-gvfs? Например, Gio::File::equal() тут не годится, ибо "two Files that differ can still refer to the same file on the filesystem due to various forms of filename aliasing". Отслеживать монтирование можно, только проку от этого мало.

**Comment by cycleg** [comment]
С начальной директорией все оказалось гораздо проще. Умные люди GVFS делают.

**Comment by unxed** [comment]
> Умные люди GVFS делают.

Вот это приятно слышать - а то на основании предыдущих обсуждений у меня уже начали закрадываться сомнения :)

>  Отслеживать монтирование можно, только проку от этого мало.

Может, вынести эту проблему в отдельный тикет?

**Comment by unxed** [comment]
Попробовал. Есть два minor bug.

1) Другие приложения видят подмонтированный ресурс sftp://HOST/folder как sftp://HOST/root. Но в far2l всё ок, и это главное :)

2) Список файлов в удаленной папке после подключения читается дважды. Если это /etc (или любая другая папка, где файлов много), а сервер в другой стране - немного мешает. Долго.

**Comment by cycleg** [comment]
Я смотрю на то, что появляется на десктопе и в Наутилусе. Они показывают "имя" подмонтированного ресурса. Хотя раньше было иначе. Не знаю, почему так. :)

По второму пункту могу сказать, что так было всегда, скорее всего. В журнал far2l дважды пишет, что ставит под наблюдение подмонтированный путь. В плагине директория панели меняется ровно один раз. Надо поглядеть в API far, может не так это делать надо?

**Comment by unxed** [comment]
На десктопе пишет HOSTNAME (MATE, Caja), но при попытке зайти - кидает в sftp://HOST/root.

Да, /root - это в смысле home folder пользователя, понятное дело, а не фиксированно именно эта строка. Когда хожу как unxed - там /home/unxed.

Так было и раньше, ага. Просто раньше не особо мешало, т.к. раньше папки с кучей файлов читались один раз, потому что заходил в них вручную, а сейчас стали дважды, потому что сразу туда кидает.

> Надо поглядеть в API far, может не так это делать надо?

Было бы здорово)

**Comment by cycleg** [comment]
С первым пунктом -- ясно. У точки монтирования есть default location на удаленной системе. И вот ее все открывают, что в общем разумно, поскольку уж оно-то откроется наверняка, если есть связь (права и все такое). В плагине же фактически заказывается доступ к ресурсу по URL, и вот на это ресурс, точнее, его проекцию в локальную файловую систему после монтирования, плагин переключает текущую панель far2l. В чем и был весь фокус с начальной директорией.

А вот с двукратным чтением есть засада. И она, видимо, где-то в far2l. Если запустить его с журналом, то она же наблюдается в tmppanel. Воспроизводится элементарно: ищем через диалог какую-нибудь директорию по имени, результат поиска выводим во временную панель, и переходим в ней на директорию. Получаем что-нибудь вроде:
```
NewDir=/home/work strCurDir=/home dot2Present=0
AddToHistory - disallowed: ''
NewDir=/home/work strCurDir=/home dot2Present=0
WinPortFSNotify('/home/work') - watching
WinPortFSNotify('/home/work') - watching
```
Вот и двукратное чтение. Такое впечатление, что метод FileList::ChangeDir() зачем-то вызывается дважды в ходе одной процедуры по смене текущей директории в панели. А, ну вот! Когда меняешь директорию через командную строку, та же песня:
```
ExplodeCmdLine('cd work/far2l'): 'cd' 'work/far2l' 
CommandLine::IntChDir: work/far2l
NewDir=/home/work/far2l strCurDir=/home dot2Present=0
WinPortFSNotify('/home/work/far2l') - watching
CommandLine::ShowBackground: done
CommandLine::SaveBackground: done
WinPortFSNotify('/home/work/far2l') - watching
```

**Comment by unxed** [comment]
Сделать тикет в far2l? Если беда не на стороне плагина.

**Comment by cycleg** [comment]
Наверное, можно. Навскидку не видно, откуда такое вылезает, но что это неправильно -- факт. При смене директории на панели способом, отличным от "штатных" (переход в директорию или смена "диска"), наблюдается такая ботва. Самый простой для исследования случай -- с командной строкой.

**Comment by cycleg** [comment]
Еще к вопросу о монтировании и путях: если заказать доступ куда-то, где не хватает прав, то увидишь пустую директорию. Если заказать то, чего нет, то получишь ошибку 2 и панель на ресурс не переключится. В обоих случаях, тем не менее, ресурс успешно смонтируется, что отразится и на панели gvfs. И в default location перейти можно, но уже не через gvfspanel (она по-прежнему будет переходить, куда заказано).

**Comment by unxed** [comment]
Это имеет смысл отразить в README.
