### ISSUE TITLE
закрытие экземпляра far2l, создавшего соединение, разрывает соединение

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#13]
если я правильно понимаю философию gvfs, разрывать соединение нужно при закрытии последнего экземпляра far2l, а не того, который создал соединение.

как воспроизвести:
1) открыть far2l
2) установить соединение с ресурсом
3) открыть второй экземпляр far2l
4) закрыть первый экземпляр far2l
5) ресурс отмонтируется, причем второй far2l будет думать, что ресурс всё ещё подмонтирован, и выдавать "error 2" при попытке "зайти" в него

**Comment by cycleg** [comment]
Теперь можно нажать на панели Ctrl-R, чтобы обновить статус всех известных ресурсов. При самом первом обращении к панели статус ресурсов проверяется автоматически.

Автоматическое отслеживание операций в GVFS возможно, но для этого надо подключаться к D-Bus, а как с такими кунштюками у плагинов far2l -- не знаю. Испытываю серьезные сомнения, что это легко реализовать. Что-то мне подсказывает: такие вещи far2l должен предоставлять плагинам, как еще одно API. В любом случае, это уже сугубо UNIX-заморочки (как с D-Bus в MacOS, например?), которые выходят за рамки портирования. Их надо прикручивать как совершенно новые, никак с оригинальным Far не связанные.

**Comment by unxed** [comment]
На правах мыслей вслух: отдельный плагин, экспортирующий соответствующие API + проверка его наличия и задействование при возможности из far-gvfs?

(: очевидно, это сложно считать первоочередной задачей :)

А ещё с d-bus можно работать из командной строки:
https://dbus.freedesktop.org/doc/dbus-monitor.1.html

**Comment by cycleg** [comment]
Специально не смотрел, но думаю, про операции по D-Bus приходят сигналы. По самой их природе где-то должен быть поток с неким циклом обработки, который будет их принимать. В отличие от GvfsService, обращения к которому по сути сделаны синхронными, а потому его можно запускать и останавливать свободно, здесь нужна асинхронность со всеми вытекающими. Не знаю, насколько архитектура far2l и плагинов для этого подходит.

**Comment by unxed** [comment]
А как far2l получает уведомления об обновлениях в файловой системе?
Для этого, по идее, нужен какой-то механизм, позволяющий асинхронность.
Вроде подписки-на-обновления.

**Comment by unxed** [comment]
не знаю, поможет ли это чем-нибудь, но можно попробовать глянуть в исходники консольного gvfs-mount. правда, там на сях всё.

https://github.com/GNOME/gvfs/blob/master/daemon/mount.c

вот пример на плюсах и его обсуждение (можно, по идее, там попробовать в комментах задать вопросы):

http://stackoverflow.com/questions/25739391/mounting-samba-share-in-c

вот ещё пример работы с gvfs из плюсов:

https://sourceforge.net/p/lufs/svn/41/tree/trunk/lufs/filesystems/gvfs/gvfs.cpp?diff=51adf6752718464efaa5053d:40&diformat=sidebyside

и ещё. кажется, в wx есть какая-то поддержка gvfs. если всё равно far2l собирается с ними, возможно, можно её использовать?

https://github.com/wxWidgets/wxWidgets/blob/master/src/gtk/gnome/gvfs.cpp

**Comment by unxed** [comment]
А можно отмонтирование ресурсов при закрытии far2l сделать отключаемой опцией в настройках? Я бы выключил до ремонта этого бага. Сильно улучшило бы user experience.

Теперь ведь можно и вручную отключать по мере необходимости.

Пока что просто закомментировал у себя содержимое Plugin::exitFar(), чтобы неожиданные пропадания ресурсов не мешали работать.

**Comment by unxed** [comment]
Перед выходом проверять, единственный ли экземпляр far2l запущен (да хотя бы через парсинг ps -A), и, если да - отмонитровать всё за собой. Если нет - не делать ничего. Вариант?

Это всяко было бы лучше, чем как сейчас.

**Comment by cycleg** [comment]
Сделать отмонтирование при выходе опциональным -- это правильно. По умолчанию пусть отмонтирует, а там пользователь сам решит. Вон Наутилус ничего за собой не размонтирует.

**Comment by unxed** [comment]
Ага, я тоже думал его в пример привести, но решил не умничать лишний раз)))

**Comment by unxed** [comment]
Спасибо! Стало совсем хорошо. Остальные баги работать практически не мешают.
