### ISSUE TITLE
не собирается на debian jessie

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#20]
`codecvt: No such file or directory.
`

Кажется, дело в тамошней версии glibcxx.

**Comment by cycleg** [comment]
Этот заголовок поддерживают в libstdc++-dev с версии 5.3. А в stable -- 4.9, засада. Делать через Boost -- громоздко, ибо там еще и ICU подтянется в зависимости. Хотя можно Boost и без нее, через iconv.

**Comment by unxed** [comment]
Ну, мне это не критично, но для кого-то может быть проблемой.

Впрочем, до тех пор, пока far2l не умеет в консоль, вряд ли его часто будут использовать на серверах.

**Comment by unxed** [comment]
Вот [здесь](https://forum.farmanager.com/viewtopic.php?p=139992#p139992) elfmz пишет:

> выпилил все #include \<codecvt\>
> но еще добавил новые зависимости. для убунты - sudo apt-get install libglib2.0-dev gawk

можно глянуть, на что он заменил использование codecvt, и сделать так же. тогда, по идее, зависимости останутся теми же.

**Comment by unxed** [comment]
> Replace std::wstring_convert with MB2Wide/Wide2MB from far2l/utils, see #14 

Вот бы ещё в README far2l дописать, что при создании плагинов лучше всего сразу делать так, чтобы собиралось на последнем дебиане.

**Comment by unxed** [comment]
Теперь собирается! Спасибо)

**Comment by unxed** [comment]
Но обнаружилось [странное](https://github.com/elfmz/far2l/issues/278).
