### ISSUE TITLE
иногда фар2л стал вылетать при обращении к плагину

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#23]
Появилось после апгрейда до минта 18.3. Опять какие-то проблемы с libc? Вылеты рандомные, с плюс-минус третьего перезапуска всё работает.

**Comment by cycleg** [comment]
Не замечал конкретно за far, но примерно 2 месяца назад в тестовом Дебиан вообще стала работать неустойчиво, такое впечатление, чуть ли не вся FUSE. Бывало, что зависала наглухо X-сессия при подмонтированной файловой системе от выключившейся виртуалки или при каком-то "неудачном" отмонтировании простой флешки. Какое-то время назад это прекратилось, как будто, но то тестовый Дебиан. В Минте вроде бы обещают стабильную работу.

Проблема из #14 никуда не делась и в glibmm 2.56. А самое гадкое в том, что у разработчиков Гнома сейчас великий переезд, по случаю чего даже генератор документации на developer.gnome.org не работает. Описаний текущих версий библиотек вообще нету.

**Comment by unxed** [comment]
И всё-таки, можно ли как-то победить это? Ну, кроме как съехать на другой дистр. Реально, адски мешает работать.

**Comment by lieff** [comment]
А пересборка (и фара и far-gvfs) после апдейта не помогает? Могли либы зависимостей обновиться, а бинари фара без изменений остались.

**Comment by cycleg** [comment]
Кстати, да, пересборка действительно может помочь.

Каждодневное использование под Дебиан testing такими проблемами не сопровождается. Не могу сказать, чтобы это кого-то оправдывало, но тем не менее. У меня навскидку не воспроизводится.

**Comment by unxed** [comment]
пересобирал неоднократно, и после upgrade, и после dist-upgrade. баг остаётся :(

выйдет 19 минт, посмотрим, что на нём будет. обещают в июне.

**Comment by lieff** [comment]
А если собрать с -g -rdynamic и запускать с catchsegv? Словится колстек?

**Comment by cycleg** [comment]
Как обычно, для победы над багом прежде всего нужно его надежное воспроизведение, чтобы был материал для исследований. Проблема может быть где угодно. У самого плагина примерно 80 зависимостей, так что гадать бессмысленно.

**Comment by unxed** [comment]
после upgrade до mint 19 воспроизводиться перестало.

**Comment by cycleg** [comment]
[Похожая история](https://github.com/elfmz/far2l/issues/254). Из чужого кода лезли ошибки.
