### ISSUE TITLE
Возможность ввести пароль при коннекте (без сохранения)

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#3]
Например, если пароль в свойствах ресурса не указан, и при коннекте происходит permission denied - давать возможность ввести пароль в процессе коннекта, не сохраняя его.

**Comment by cycleg** [comment]
Идея в том, чтобы назначить запрос пароля при каждом монтировании. Соответственно, если эта опция задана, введенный при редактировании ресурса пароль игнорируется и не хранится. С другой стороны, если не включать эту опцию, то можно подключаться с пустым паролем (для любителей экстрима).

Если указать эту опцию при пустых пользователе и пароле, возникнет ошибка, ибо суровому Анонимусу пароль не к лицу.

**Comment by unxed** [comment]
Спасибо! А можно очищать и деактивировать поле ввода пароля при установленной галке? 

btw, в netbox, если мне не изменяет память, та же задача решена галкой "режим сурового Анонимуса". Допускаю, что новоприбывшим гостям-с-винды такой вариант может показаться более интуитивным (хотя мне ваш вариант кажется логичнее).

**Comment by unxed** [comment]
Спасибо! А можно при деактивированном поле ввода пароля слово Password делать сереньким? "Options"-"System settings" ведет себя так с подписями к не активным полям. Пусть будет единообразие интерфейса.

**Comment by unxed** [comment]
Супер!
