### ISSUE TITLE
Editing text file on FTP resource containing "/" character makes those characters removed

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#31]
1. Mount FTP resource
2. Switch to it's panel
3. Press Shift+F4
4. Type "test.txt"
5. Press Enter
6. Type "/"
7. Press F2
8. Press Esc
9. Edit test.txt (F4) - no "/" char.

**Comment by unxed** [comment]
charset issue, closing

**Comment by unxed** [comment]
Actually, any edit ruins files. Seems like some charset issue, but could not guess how to fix it.

"/" is written, just not shown then reopening file in editor.

Manually switching from ANSI to UTF8 and back to ANSI fixes it.

No problems then copying file to local FS and editing it there.

For latin-encoded files like robots.txt utf8/ansi should not make any difference. But for some reason it does.

**Comment by cycleg** [comment]
С sftp ресурсом такого не наблюдаю. Создается, сохраняется и затем редактируется без проблем.

Может быть счастье в том, чтобы по умолчанию была UTF-8? Кажется, где-то кодировку по умолчанию для редактора можно задать.

**Comment by unxed** [comment]
С sftp у меня тоже всё ок. Все галки про кодировки в настройках уже перепробовал, разумеется :)

Стоп. А если примонитроваться вообще не через плагин? Ща проверю.

**Comment by unxed** [comment]
Да, тот же баг. Значит, беда фара, а не плагина.

**Comment by unxed** [comment]
Уточнение. С галкой autodetect code page при редактирвоании чего-то длинее 1 байта получаем вообще пустой файл в редакторе. Без - съедается часть текста вначале. Галки про utf8 влияния не оказывают.

**Comment by unxed** [comment]
Сделал новый, лаконичный тикет с понятной инструкцией по воспроизведению косяка.

elfmz/far2l#515
