### ISSUE TITLE
При попытке редактирования ресурса, URL которого начинается с цифры, редактируется другой ресурс

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#5]
Например, если добавить хост без префикса sftp://, то при попытке отредактировать запись о ресурсе редактируется другая запись.

**Comment by cycleg** [comment]
Это как? Вот я завожу ресурс с URL "test". По F4 редактируется он, а не какой-либо другой. Удаляется тоже он. В чем проблема?

Если же рассмотреть предложение в целом, то по-моему пытаться верифицировать URL в данном случае нет особого смысла, ибо плагин суть обертка над имеющимися средствами GVFS. Если URL имеет смысл, и GVFS его поддерживает, то с ним можно будет делать что-то полезное, иначе нет никакого смысла держать непригодную запись. Ее выкинут или исправят, и верификация силами плагина тут -- пятое колесо в телеге.

**Comment by unxed** [comment]
Эксперименты показали, что проблема с редактированием возникает, если URL начинается с цифры. Попробуйте URL "5", например.

Удаление работает нормально в любом случае.

Верификация URL была просто первой пришедшей в голову идеей "как такое предотвратить".

**Comment by cycleg** [comment]
Там проблема совсем другого рода. Far запрашивает у плагина список элементов панели. Плагин его отдает, но на панель far их выводит не в порядке перечисления, а в каком-то другом. В итоге на редактирование попадает совсем не тот элемент. А при попытках подмонтировать вызывается другая функция, и в нее попадает то, что нужно. Почему так -- пока не понимаю.

**Comment by unxed** [comment]
Предполагал что-то подобное.

Это совсем не критично и пользоваться не мешает, но я решил, что всё-таки правильно будет оформить issue.
