### ISSUE TITLE
Реализовать правильную обработку сигнала ask_question при монтировании ресурса

### ISSUE THREAD

**Issue by unxed** [cycleg/far-gvfs#6]

**Comment by unxed** [comment]
Вероятно, проблема в том, что gvfs хочет, чтобы хост был в ~/.ssh/known_hosts

**Comment by cycleg** [comment]
Проблема в том, что в ходе подключения пользователю могут задавать вопрос (вопросы) с вариантами ответов. Выбирается один из и передается в GVFS. Первое подключение с новым ключом -- один из случаев. Но callback для выбора ответа вызывает ошибку с распределением памяти неясной природы. Похоже, там дважды высвобождается одно и то же. Видимо, что-то callback делает не так.

**Comment by cycleg** [comment]
По косвенным признакам, проблема все-таки где-то в giomm, в C++ обертке над C-библиотекой, ибо использующая только C-интерфейс gvfs-mount работает. Там по очереди должны вызываться два callback'а: задать вопрос пользователю и получить ответ, и спросить пароль. Первый отрабатывается нормально: скажешь продолжать -- хост помещают в известные SSH, скажешь не продолжать -- он там не появляется. Но потом должен вызваться в первом варианте callback про пароль, во втором -- завершающий всю операцию подключения. Все это происходит где-то в недрах glib и ее обвязок, код приложения уже не при делах. Где-то там и засада. Поиск похожих ошибок результатов не дал.

Примечательно, что если вариант ответа по умолчанию 0 вдруг "подошел" и хост прописали как известный, то при следующей попытке монтирование может и прокатить.

**Comment by unxed** [comment]
Тикет в GNOME? Если нужно перевести на англ., я готов. Но нужен текст, сформулированный именно как багрепорт. Со сценарием воспроизведения.

И ещё я бы посмотрел, например, в код caja, как сделано там. Идеалогически там всё то же самое, что у нас.

**Comment by cycleg** [comment]
Крепнет убеждение, что в чужом коде проблемы. Соорудил тестовую программу в 25 строк плюс кусок кода из плагина, который монтирует ресурс, еще строк 200. Прогнал с valgrind'ом, тот подтверждает лажу.
[memchk.txt](https://github.com/cycleg/far-gvfs/files/968136/memchk.txt)
Особенно 70-ая строка характерна. Вот почему гикнулось после ask_question: варианты приходят в контейнере Glib::StringArrayHandle, а потом где-то что-то не вовремя удаляется. Или пытаются извлечь то, что удалилось вместе с контейнером. Может скопировать забыли, или правда дважды пытаются удалить.

На самом деле, все, что делает код в обработке трефного сигнала -- выводит тексты и выдает подтверждение, мол, пили дальше. Накосячить просто негде.

**Comment by unxed** [comment]
Я б глянул, как сделано у других. gvfs не мы одни используем. Как-то, видать, обходят этот баг.

**Comment by unxed** [comment]
Возможно, есть смысл закинуть репорт сюда:
https://bugzilla.gnome.org/page.cgi?id=browse.html&product=glibmm

**Comment by unxed** [comment]
Больше не вылетает. Спасибо! :)

**Comment by cycleg** [comment]
Кривой безобразный объезд Glib::StringArrayHandle. Через C-интерфейс glib заработало, но теперь GvfsService не потокобезопасный. В качестве заплатки сойдет. Пацаны совсем убрали Glib::StringArrayHandle в версии 2.53, но она -- текущая и нестабильная, поэтому в Debian до сих пор 2.50. Выпустят стабильную, поменяют в Debian, тогда можно проверить. Ну или собрать far-gvfs в какой-нибудь Убунте, где glibmm 2.53 есть. Сейчас вариант C++ закомментирован, можно переделать на условную компиляцию по версии glibmm.

Падать перестало, т.е. пользоваться можно. Следующий шаг: показывать вопрос пользователю и передавать его выбор.

**Comment by unxed** [comment]
Я читал код) А сделать условную компиляцию и оставить тикет до корректной реализации - разумно, согласен.

**Comment by cycleg** [comment]
Самое сильное вуду -- в [GvfsService.cpp](https://github.com/cycleg/far-gvfs/blob/83a414d9c160ea7bf3f905178d8c000a10da0446/src/GvfsService.cpp). Магия пары g_main_context_push_thread_default()/g_main_context_pop_thread_default() до конца не прояснилась. Но без нее не работает пользовательский ввод.

**Comment by unxed** [comment]
:)

Проверил. Спрашивает. Круть)

> При получении во время монтирования ресурса сигнала ask_question всегда выбирается вариант ответа по умолчанию. Подробнее в #6.

Это всё ещё нужно в README?

**Comment by unxed** [comment]
Нужен ли отдельный тикет на потокобезопасность, чтобы-не-забыть, или это уже избыточно?
